config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '(:path)(/:id)' => 'home#index'
  end

  namespace :api do
    resources :questionnaires, only: [:index, :create, :show]
  end

  resources :questionnaires, only: [:index, :show] do
    member do
      post 'submit' => 'questionnaires#submit'
      get 'thanks' => 'questionnaires#thanks'
    end
  end

  root to: redirect('/questionnaires')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/questionnaire.rb
# frozen_string_literal: true

class Questionnaire < ApplicationRecord
  has_many :questionnaire_responses
end

app/models/questionnaire_response.rb
# frozen_string_literal: true

class QuestionnaireResponse < ApplicationRecord
  belongs_to :questionnaire
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

module Admin
  class HomeController < ApplicationController
    layout 'admin'

    def index
    end
  end
end

app/controllers/api/questionnaires_controller.rb
## frozen_string_literal: true

module Api
  class QuestionnairesController < ApplicationController
    def index
      render json: { questionnaires: Questionnaire.all.as_json(only: [:id, :title]) }
    end

    def create
      questionnaire = Questionnaire.create(questionnaire_params)

      render json: {
        result: {
          message: 'Questionnaire created'
        },
        record: QuestionnaireAsJson.new(
          questionnaire,
          url: questionnaire_url(questionnaire)
        )
      }
    end

    def show
      render json: QuestionnaireWithResponsesAsJson.new(
        Questionnaire.find(params[:id])
      ).as_json
    end

    private

    def questionnaire_params
      params.require(:questionnaire).permit(:title, questions: [:name, :label])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questionnaires_controller.rb
# frozen_string_literal: true

class QuestionnairesController < ApplicationController
  helper_method :questionnaire, :questionnaire_form

  def index
    @questionnaires = Questionnaire.all.order(:title)
  end

  def show
  end

  def submit
    SubmitQuestionnaire
      .new(questionnaire_form)
      .call(questionnaire_response_params) do |response|
      response.on(:success) do
        redirect_to thanks_questionnaire_url(questionnaire)
      end

      response.on(:validation_error) do
        render 'show'
      end
    end
  end

  def thanks
  end

  private

  def questionnaire_form
    @questionnaire_form ||= QuestionnaireForm.new(questionnaire)
  end

  def questionnaire
    @questionnaire ||= Questionnaire.find(params[:id])
  end

  def questionnaire_response_params
    @questionnaire_response_params ||= params.require(:questionnaire_form).permit(questionnaire_form_fields)
  end

  def questionnaire_form_fields
    [:person_name] + questionnaire_form.questions.collect(&:form_field)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/home/index.html.erb
<div id="admin-app"></div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container">
    <%= link_to 'Questionnaires', root_url, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_url, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Admin
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Home', admin_url, class: 'dropdown-item' %>
            <%= link_to 'Add questionnaire', admin_url(path: 'add-questionnaire'), class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questionnaires</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'admin' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questionnaires</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questionnaires/index.html.erb
<h1>Questionnaires</h1>

<% if @questionnaires.empty? %>
  <p>There are no questionnaires configured</p>
  <p>Visit <%= link_to 'the admin area', admin_url %> to set one up</p>
<% else %>
  <p>
    Select a questionnaire to complete or visit <%= link_to 'the admin area', admin_url %> to
    set up a new one.
  </p>

  <% @questionnaires.each do |questionnaire| %>
    <p>
      <%= link_to questionnaire.title, questionnaire_url(questionnaire) %>
    </p>
  <% end %>
<% end %>

app/views/questionnaires/show.html.erb
<h1><%= questionnaire_form.title %></h1>

<%= simple_form_for questionnaire_form, url: submit_questionnaire_path, html: { class: 'form' } do |form| %>

  <%= form.input :person_name, label: 'Please enter your name', required: true %>

  <% questionnaire_form.questions.each do |question| %>
    <%= form.input question.form_field, label: question.label, required: true %>
  <% end %>

  <%= form.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/questionnaires/thanks.html.erb
<h1><%= questionnaire.title %></h1>

<p>
  Thank you for submitting the questionnaire
</p>